---
title: "Yelp ShinyApps - wordcloud"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
runtime: shiny
---
```{r setup, include=FALSE}
pacman::p_load(flexdashboard,shinyWidgets,wordcloud2,dplyr,shinythemes,lubridate)
load("data/Bmx.RData");load("data/rev_id.RData")

##spark
library(dplyr) 
library(sparklyr)
Sys.setenv(SPARK_HOME="/usr/local/spark/spark-2.1.0-bin-hadoop2.7/")
Sys.setenv(SPARK_HOME="/usr/local/spark/spark-2.4.5-bin-hadoop2.7")
config <- spark_config()
config$spark.executor.memory = "32G"
config$spark.driver.memory = "32G"
config$spark.yarn.executor.memoryOverhead = "4096"
config$spark.cores.max = "64"
config$spark.dynamicAllocation.enabled="true"
config$spark.dynamicAllocation.executorIdleTimeout="120s"
sc = spark_connect(master = "spark://hnamenode:7077", config = config)

#####
dtm <- spark_read_parquet(sc, "dtm", "/home/sum2020/yelp/matrix")
# quantile(colSums(Bmx), seq(0.8,1,0.02))
# cate <- colnames(Bmx)[(colSums(Bmx)>1000)]


cate <- colnames(Bmx)[order(colSums(Bmx), decreasing = TRUE)]


```



Column
-------------------------------------
    

### 文字雲-1
```{r}

dropdown(
        tags$h3("List of Inputs"),
        actionButton("go", label = "Go!!", class = "btn-primary"),
        
        selectInput("Yb", label = "Year",
              choices = 2004:2019, selected = 2018),
        # pickerInput(
        #   inputId="Cat", 
        #   label = "選擇主題", 
        #   choices = cate,
        #   selected = sample(cate,2),
        #   options = list(`actions-Box` = TRUE,
        #                  `live-search`=TRUE, 
        #                  style="btn-primary"),
        #   multiple = TRUE
        # ),
        selectInput(
          "Cat",label = "category",
          choices = cate,
          selected=head(cate, 10)[5],
          multiple = TRUE
        ),
         sliderInput("sldb", label = "amount", min = 10, 
        max = 750, value = 200),
        sliderInput("Mb1",  "詞頻遮罩",  0, 100, 25, 1),
        sliderInput("Mb2",  "個數遮罩",  0, 20, 5, 1),
        
        prettyRadioButtons(
              "Sqrtb", "字頻開更號", choices = list("是"=1, "否"=0),
              selected = 1, inline=T, icon=icon("check"), 
              status="success", animation="jelly"),
        
        circle = TRUE, status = "danger",
        inputId = "mydropdown",
        icon = icon("gear"), width = "300px"
      )

# input <- list(Cat = sample(cate,2), Yb = 2017, sld1 = 200, Mb1 = 25, Mb2 = 5)
B = eventReactive(input$go, {
  idx <- rownames(Bmx)[rowSums(as.matrix(Bmx[,which(cate %in% input$Cat)]))>0]
  
  rid <- rev_biz_id %>% 
    filter(lubridate::year(date)==as.numeric(input$Yb),
           business_id %in% idx
           ) %>% 
    pull(rid)
  
  wc<- dtm %>% 
    select(doc_id, lemma, freq) %>% 
    filter(as.integer(doc_id) %in% rid) %>% 
    group_by(lemma) %>% 
    summarise(freq = sum(freq, na.rm = TRUE)) %>% 
    rename(word = lemma)
  
  wc <- wc %>% arrange(desc(freq)) %>% head(input$sldb)
    
  wc <-  collect(wc)
  
  wc <- wc %>% 
    filter(freq > quantile(wc$freq, probs = input$Mb1/100)) %>% 
    slice((1+input$Mb2):nrow(wc)) 
  
  if(input$Sqrtb == "1") wc$freq = sqrt(wc$freq)
  wc
})


renderWordcloud2(
  wordcloud2(
    B()
    )
  )  





```   

Column
-------------------------------------
   
### 文字雲-2

```{r}
dropdownButton(
        tags$h3("List of Inputs"),
        actionButton("goA", label = "Go!!", class = "btn-primary"),
        
        selectInput("Ya", label = "Year",
              choices = 2004:2019, selected = 2017),
        selectInput(
          "Cata",label = "category", 
          choices = cate,
          selected=head(cate, 10)[8],
          multiple = TRUE
        ),
        sliderInput("slda", label = "amount", min = 10, 
        max = 750, value = 200),
        sliderInput("Ma1",  "前端(高頻)遮罩",  0, 20, 1, 1),
        sliderInput("Ma2",  "末端(低頻)遮罩",  0, 20, 2, 1),
        
        prettyRadioButtons(
              "Sqrta", "字頻開更號", choices = list("是"=1, "否"=0),
              selected = 1, inline=T, icon=icon("check"), 
              status="success", animation="jelly"),
        
        circle = TRUE, status = "danger",
        inputId = "mydropdown",
        icon = icon("gear"), width = "300px"
      )

A = eventReactive(input$goA, {
  #reactive({
  idx <- rownames(Bmx)[rowSums(as.matrix(Bmx[,which(cate %in% input$Cata)]))>0]
  
  rid <- rev_biz_id %>% 
    filter(lubridate::year(date)==as.numeric(input$Ya),
           business_id %in% idx
           ) %>% 
    pull(rid)
  
  wc_a<- dtm %>% 
    select(doc_id, lemma, freq) %>% 
    filter(as.integer(doc_id) %in% rid) %>% 
    group_by(lemma) %>% 
    summarise(freq = sum(freq, na.rm = TRUE)) %>% 
    rename(word = lemma)
  
  wc_a <- wc_a %>% arrange(desc(freq)) %>% head(input$slda)
  
  wc_a <-  collect(wc_a)
  
  wc_a <- wc_a %>% 
    filter(freq > quantile(wc_a$freq, probs = input$Ma1/100)) %>% 
    slice((1+input$Ma2):nrow(wc_a))
  
  if(input$Sqrta == "1") wc_a$freq = sqrt(wc_a$freq)
  wc_a
  })
renderWordcloud2(
  wordcloud2(
    A()
    )
)
```   
